spring: 
    application: 
        name: userservice
    datasource:
        url: jdbc:mysql://localhost:3306/user?characterEncoding=utf8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
