server: 
    port: 8081
eureka:
  client:
    serviceUrl:
      registerWithEureka: true 
      fetchRegistry: false  #是否允许客户端抓取eureka的注册信息
      defaultZone: http://localhost:8761/eureka/
spring: 
    application: 
        name: userservice
    datasource:
        url: jdbc:mysql://localhost:3306/user?characterEncoding=utf8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        